# Generated by Django 4.1.1 on 2022-09-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date when Note added')),
                ('name', models.CharField(help_text='Short name of your Note', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Add here all you want to remember', max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter category name for your note (e.g. Important)', max_length=100, unique=True, verbose_name='Category')),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mynotes.note')),
            ],
        ),
    ]
