# Generated by Django 4.1.1 on 2022-09-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_remove_category_note_note_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
