# Generated by Django 4.1.1 on 2022-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Add here all you want to remember', max_length=2000, verbose_name='Description'),
        ),
    ]
