# Generated by Django 4.1.1 on 2022-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0006_alter_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Picture'),
        ),
    ]
