# Generated by Django 4.1.1 on 2022-09-11 14:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0010_category_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Add here all you want to remember', max_length=2000, verbose_name='Description'),
        ),
    ]
