# Generated by Django 4.1.1 on 2022-09-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0012_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Enter category name for your note (e.g. Important)', max_length=100, unique=True, verbose_name='Category'),
        ),
    ]
