# Generated by Django 4.1.1 on 2022-09-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0014_newcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCategory',
        ),
    ]
