# Generated by Django 4.1.1 on 2022-09-12 21:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0015_delete_newcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Add date in format (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
