# Generated by Django 4.1.1 on 2022-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0016_alter_note_date_alter_note_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Picture'),
        ),
    ]
